"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path
from dotenv import load_dotenv

# Suppress 3rd-party library deprecation warnings (e.g. razorpay pkg_resources)
warnings.filterwarnings("ignore", message=".*pkg_resources is deprecated.*")
warnings.filterwarnings("ignore", category=UserWarning, module=".*razorpay.*")
warnings.filterwarnings("ignore", category=DeprecationWarning, module=".*pkg_resources.*")

BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / '.env')

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY') or os.getenv('SECRET_KEY', 'django-insecure-default-change-me-in-env')
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

# Base allowed hosts for local development and PythonAnywhere deployment
DEFAULT_ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'sneh1205.pythonanywhere.com',
    '.pythonanywhere.com',
]

# Read optional additional hosts from environment (comma-separated), excluding wildcard '*'
_env_hosts = [
    h.strip()
    for h in os.getenv('ALLOWED_HOSTS', '').split(',')
    if h.strip() and h.strip() != '*'
]

# Combine default hosts with environment hosts, preserving order and uniqueness
ALLOWED_HOSTS = list(dict.fromkeys(DEFAULT_ALLOWED_HOSTS + _env_hosts))


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'workshop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Workshop Business Information & Invoice Configurations
from decimal import Decimal
WORKSHOP_NAME = os.getenv('WORKSHOP_NAME', 'AutoFixPro Workshop')
WORKSHOP_LEGAL_ENTITY = os.getenv('WORKSHOP_LEGAL_ENTITY', 'AutoFixPro Technologies Inc.')
WORKSHOP_ADDRESS = os.getenv('WORKSHOP_ADDRESS', '101, AutoFixPro Plaza, SG Highway, Ahmedabad, Gujarat 380054')
WORKSHOP_PHONE = os.getenv('WORKSHOP_PHONE', '+91 98765 43210')
WORKSHOP_EMAIL = os.getenv('WORKSHOP_EMAIL', 'support@autofixpro.com')
WORKSHOP_GSTIN = os.getenv('WORKSHOP_GSTIN', '24AAACA1234F1Z9')
GST_RATE = Decimal(os.getenv('GST_RATE', '18.00'))



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"
# Enable WhiteNoise compression and caching for fast, reliable static serving in production
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Media files (User uploaded images and documents)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Razorpay API Credentials
RAZORPAY_KEY_ID = os.getenv('RAZORPAY_KEY_ID', '').strip()
RAZORPAY_KEY_SECRET = os.getenv('RAZORPAY_KEY_SECRET', '').strip()

# ============================================================
# EMAIL / OTP PRODUCTION CONFIGURATION
# ============================================================
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '').replace(' ', '').strip()
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', f"AutoFixPro <{EMAIL_HOST_USER}>" if EMAIL_HOST_USER else "AutoFixPro <noreply@autofixpro.com>")
SERVER_EMAIL = os.getenv('SERVER_EMAIL', EMAIL_HOST_USER)
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', 15))

# HTTP REST Email APIs (Works 100% on PythonAnywhere Free Tier over HTTPS port 443)
BREVO_API_KEY = os.getenv('BREVO_API_KEY', '').strip()
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '').strip()
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL', '').strip()
DEFAULT_FROM_NAME = os.getenv('DEFAULT_FROM_NAME', 'AutoFixPro').strip()

# OTP Security Parameters
EMAIL_OTP_EXPIRY_MINUTES = int(os.getenv('EMAIL_OTP_EXPIRY_MINUTES', 5))
EMAIL_OTP_RESEND_SECONDS = int(os.getenv('EMAIL_OTP_RESEND_SECONDS', 30))
EMAIL_OTP_RESEND_COOLDOWN = int(os.getenv('EMAIL_OTP_RESEND_COOLDOWN', EMAIL_OTP_RESEND_SECONDS))
EMAIL_OTP_MAX_RESENDS = int(os.getenv('EMAIL_OTP_MAX_RESENDS', 5))
EMAIL_OTP_MAX_ATTEMPTS = int(os.getenv('EMAIL_OTP_MAX_ATTEMPTS', 5))

# ============================================================
# PRODUCTION DEPLOYMENT & SECURITY SETTINGS (Step 9)
# ============================================================

# Trust PythonAnywhere and cloud reverse proxies for HTTPS detection
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Session security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 7 days
SESSION_COOKIE_SECURE = not DEBUG

# CSRF security
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG

# CSRF Trusted Origins for live domain/hosting (Includes PythonAnywhere and localhost)
_env_origins = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if origin.strip()]
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys([
    'https://sneh1205.pythonanywhere.com',
    'http://sneh1205.pythonanywhere.com',
    'https://*.pythonanywhere.com',
    'http://*.pythonanywhere.com',
    'https://*.ngrok-free.app',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
] + _env_origins))

# SSL Redirect (Enable in production once SSL/HTTPS domain is live)
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False').lower() in ('true', '1', 't') if not DEBUG else False

# HSTS (HTTP Strict Transport Security)
if not DEBUG and os.getenv('ENABLE_HSTS', 'False').lower() in ('true', '1', 't'):
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Browser Security Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"
SECURE_REFERRER_POLICY = "same-origin"

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


