# Generated by Django 6.0.7 on 2026-08-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_inventory_alter_payment_id_alter_servicebooking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshop.servicebooking'),
        ),
    ]
