# Generated by Django 6.0.7 on 2026-08-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_emailotp_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
