# Generated by Django 6.0.8 on 2026-09-29 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0013_alter_contactmessage_id_alter_emailotp_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='otp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('RAZORPAY', 'Razorpay Online'), ('CASH', 'Cash')], default='UPI', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Paid', 'Paid'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refund Pending', 'Refund Pending'), ('Refunded', 'Refunded')], default='Created', max_length=30),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('In Progress', 'In Progress'), ('Quality Check', 'Quality Check'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicereview',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
