# Generated by Django 5.1.15 on 2026-09-30 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0014_payment_paid_at_alter_emailotp_otp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_used', to='workshop.servicebooking')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_usages', to='workshop.inventory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
